
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import React, {useState} from "react";
import Footer from "@/components/common/Footer/index";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      {/* <body className={inter.className}> */}
      <body>
        <div className='px-12 max-w-screen-xl mx-auto'>
          <main>{children}</main>
          <ToastContainer />
        </div>
        <div className=' bg-gray-900'>
          <Footer />
        </div>
      </body>
    </html>
  );
}
